### PR TITLE
Mandala blog topic by Saachi Kaup

### PR DESCRIPTION
**Pull request by yaxu**

### CODE REVIEW

**Comment by yaxu** [comment]
@HighHarmonics2 does this look ok to you?

**Comment by HighHarmonics2** [comment]
@yaxu 
It is great to have this blog post on the Mandala topic, with details, code and examples. My one suggestion is to add something at the top to provide context. Something along the lines of:

Note: Saachi Kaup participated in the Haskell Summer of Code with a project to [research creating mandala visual patterns in Haskel](https://algorithmicpattern.org/2023/05/12/summer-contributor-saachi-kaup-on-mandala-patterns/), and integrating them in TidalCycles.  Her work <detail> ..... This blog post represents a summary of her work .... <detail>.

**Comment by HighHarmonics2** [comment]
@yaxu 
Alternatively, you could ask Saachi to write a short intro, something like what Lizzy Wilson provided in her Summer of Haskell project: https://blog.tidalcycles.org/index.html%3Fp=1280.html

**Comment by yaxu** [comment]
@HighHarmonics2 Apologies for the delay, I've now added a short intro provided by Saachi.

**Comment by HighHarmonics2** [comment]
I'll merge and publish this. I'll check for any Docusaurus or workflow errors.

**Pull request merged**
