### PR TITLE
add miUgens synth parameter reference

### PR DESCRIPTION
**Pull request by cleary**
Also split the installation manual to a separate page
Need to check the internal links once it goes live

### CODE REVIEW

**Comment by Zalastax** [comment]
Looks good!

Is the rename to mi-UGens done because there is no affiliation with Mutable Instruments?

> Need to check the internal links once it goes live

Just for my understanding - is this because you've not verified the change on a local development environment?

**Comment by cleary** [comment]
> Looks good!
> 
> Is the rename to mi-UGens done because there is no affiliation with Mutable Instruments?

Yeah, while doing a more thorough search for documentation I came across the bit in the main github repo which was very explicit about not using the term Mutable Instruments in association with any derivatives. To this point, I hadn't been strict about it -
 
> > Need to check the internal links once it goes live
> 
> Just for my understanding - is this because you've not verified the change on a local development environment?

Yes - I completely spaced on the fact that I can do that! let me give it a test here before you push it (and thanks for the detailed look)

**Comment by cleary** [comment]
Ok, everything checked, links are working - slight formatting tidy up done and it's good :+1:

**Comment by Zalastax** [comment]
Awesome! I understand we are ready to merge?

**Comment by cleary** [comment]
> Awesome! I understand we are ready to merge?

Yes please 👍

**Pull request merged**
