### PR TITLE
Overhaul / reorganization

### PR DESCRIPTION
**Pull request by Bubobubobubobubo**
I have some extra energy this week. I spent the last three days working on the transition from the old docs to the new documentation. It's far from perfect, and there are still a lot of things to import / format but I think that it's better already. 

I reworked a lot of things (organization, landing page, sidebar, etc...).

### CODE REVIEW

**Comment by yaxu** [comment]
Ok to merge first and see how it goes?

**Comment by Bubobubobubobubo** [comment]
You can merge. I'll update it more gradually from now on.

**Comment by yaxu** [comment]
Thanks!

**Comment by yaxu** [comment]
There were some problems with deployment keys but it's live now ! https://doc.tidalcycles.org/

**Pull request merged**
